### ISSUE TITLE
Update Playbook for Uberspace 7

### ISSUE THREAD

**Issue by dennzimm** [yeah/ansible-uberspace#1]

**Comment by The-Compiler** [comment]
FWIW I wrote something for domains. Disclaimer: It's quite a hack, tailored to my setup and relies on uberspace internals.

```yml
---

- name: Fetch uberspace domains
  fetch:
    src: /opt/uberspace/userfacts/{{ ansible_user }}/domains.yml
    dest: tmp/{{ inventory_hostname }}/
    flat: true
    fail_on_missing: false
  register: fetch_result

- name: Read uberspace domains
  include_vars:
    file: tmp/{{ inventory_hostname }}/domains.yml
    name: remote_domains
  when: fetch_result.changed

- name: Set uberspace domain defaults
  set_fact:
    remote_domains: []
  when: not fetch_result.changed

#---------

- name: Add new domains
  loop: "{{ uberspace_domains|product(['web', 'mail'])|list }}"
  when: item[0] not in remote_domains
  command: uberspace {{ item[1] }} domain add {{ item[0] }}
  register: add_output

- name: Print output
  loop: "{{ add_output.results|list }}"
  when: item.changed
  debug:
    msg: "{{ item['stdout_lines'] }}"

- name: Add www domains
  loop: "{{ uberspace_domains }}"
  when: '"www." + item not in remote_domains and item|select("equalto", ".")|list|length == 1'
  command: uberspace web domain add www.{{ item }}

- name: Remove old domains
  loop: "{{ remote_domains|product(['web', 'mail'])|list }}"
  when: '"www." not in item[0] and item[0] not in uberspace_domains'
  command: uberspace {{ item[1] }} domain del {{ item[0] }}

- name: Remove old www domains
  loop: "{{ remote_domains|list }}"
  when: '"www." in item and item|replace("www.", "") not in uberspace_domains'
  command: uberspace web domain del {{ item }}

```
